# Generated by Django 3.0.5 on 2020-05-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_auto_20200501_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchingdata',
            old_name='Dscription',
            new_name='Description',
        ),
    ]
