# Generated by Django 3.0.5 on 2020-05-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0004_unkownsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='unkownsearch',
            name='ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='searching.Category', verbose_name='Category'),
        ),
    ]
