# Generated by Django 3.0.5 on 2020-05-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0006_auto_20200502_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unkownsearch',
            name='ID',
        ),
    ]
