# Generated by Django 3.0.5 on 2020-05-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0007_remove_unkownsearch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unkownsearch',
            name='ID',
            field=models.IntegerField(default=0),
        ),
    ]
