# Generated by Django 3.0.5 on 2020-05-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0008_unkownsearch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unkownsearch',
            old_name='ID',
            new_name='unknownID',
        ),
    ]
