# Generated by Django 3.0.5 on 2020-05-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0009_auto_20200502_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unkownSearch',
        ),
    ]
