# Generated by Django 3.0.5 on 2020-05-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0011_unknownsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('status', models.CharField(max_length=8)),
            ],
        ),
    ]
