# Generated by Django 3.0.5 on 2020-05-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0012_commentanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentAnalysis',
        ),
    ]
