# Generated by Django 3.0.5 on 2020-05-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0013_delete_commentanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=200)),
                ('comment', models.TextField(max_length=400)),
                ('status', models.CharField(max_length=8)),
            ],
        ),
    ]
